{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"domainError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"URL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLError","preciseIdentifier":"s:10Foundation8URLErrorV"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":2,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/apiclient\/apiclienterror\/domainerror(url:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/dev.jano.apiclient\/documentation\/APIClient\/APIClientError\/domainError(URL:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"NSError in the URLError domain. This is thrown by Apple’s networking code."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"domainError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"URL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLError","preciseIdentifier":"s:10Foundation8URLErrorV"},{"kind":"text","text":")"}],"title":"APIClientError.domainError(URL:)","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:9APIClient0A5ErrorO06domainB0yAC10Foundation8URLErrorV_tcACmF","modules":[{"name":"APIClient"}]},"hierarchy":{"paths":[["doc:\/\/dev.jano.apiclient\/documentation\/APIClient","doc:\/\/dev.jano.apiclient\/documentation\/APIClient\/APIClientError"]]},"references":{"doc://dev.jano.apiclient/documentation/APIClient":{"role":"collection","title":"APIClient","abstract":[],"identifier":"doc:\/\/dev.jano.apiclient\/documentation\/APIClient","kind":"symbol","type":"topic","url":"\/documentation\/apiclient"},"doc://dev.jano.apiclient/documentation/APIClient/APIClientError":{"role":"symbol","title":"APIClientError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"APIClientError"}],"abstract":[{"type":"text","text":"Errors thrown by the APIClient."}],"identifier":"doc:\/\/dev.jano.apiclient\/documentation\/APIClient\/APIClientError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"APIClientError"}],"url":"\/documentation\/apiclient\/apiclienterror"},"doc://dev.jano.apiclient/documentation/APIClient/APIClientError/domainError(URL:)":{"role":"symbol","title":"APIClientError.domainError(URL:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"domainError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"URL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLError","preciseIdentifier":"s:10Foundation8URLErrorV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"NSError in the URLError domain. This is thrown by Apple’s networking code."}],"identifier":"doc:\/\/dev.jano.apiclient\/documentation\/APIClient\/APIClientError\/domainError(URL:)","kind":"symbol","type":"topic","url":"\/documentation\/apiclient\/apiclienterror\/domainerror(url:)"}}}